pub mod alias_access;
pub mod bogus_control_flow;
pub mod clone_function;
mod custom_calling_conv;
pub mod flatten;
pub mod function_wrapper;
pub mod indirect_branch;
pub mod indirect_call;
pub mod lower_switch;
pub mod mba;
pub mod shuffle_blocks;
pub mod split_basic_block;
pub mod string_encryption;
pub mod vm_flatten;
